/**
 * Webhook Routes — Yukk Payment Provider Callbacks
 *
 * These routes are called BY Yukk (not by Zuka members).
 * No member auth (requireAuth) is applied.
 *
 * Endpoints:
 * - POST /v1.0/qr/qr-mpm-notify  — Payment notification callback
 * - POST /v1.0/access-token/b2b   — B2B access token exchange
 */

import { Hono } from "hono";
import crypto from "node:crypto";
import { db } from "../db/index.js";
import { paymentTransaction, subscription } from "../db/schema.js";
import { eq } from "drizzle-orm";
import {
  verifyYukkWebhookSignature,
  normalizeYukkWebhook,
  generateTimestamp,
  generateAccessTokenSignature,
  type YukkRawWebhookBody,
} from "../lib/yukk.js";
import { activateSubscription } from "../lib/subscription-activation.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type SnapResponse = {
  responseCode: string;
  responseMessage: string;
};

type B2bTokenResponse = SnapResponse & {
  accessToken: string;
  tokenType: string;
  expiresIn: string;
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isFakeMode(): boolean {
  return process.env.PAYMENT_PROVIDER_MODE === "fake";
}

function snapSuccess(code = "2005200"): SnapResponse {
  return { responseCode: code, responseMessage: "Successful" };
}

function snapError(code: string, message: string): SnapResponse {
  return { responseCode: code, responseMessage: message };
}

/**
 * Generate a signed JWT access token for B2B partner use.
 * Uses HMAC-SHA256 (HS256) with a shared secret from env.
 */
function generateB2bJwt(): string {
  const secret = process.env.YUKK_B2B_JWT_SECRET ?? "zuka-b2b-jwt-secret-dev";
  const now = Math.floor(Date.now() / 1000);

  const header = Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT" })).toString("base64url");
  const payload = Buffer.from(
    JSON.stringify({
      iss: "zuka-api",
      aud: "yukk-partner",
      iat: now,
      exp: now + 900, // 15 minutes
    }),
  ).toString("base64url");

  const signature = crypto
    .createHmac("sha256", secret)
    .update(`${header}.${payload}`)
    .digest("base64url");

  return `${header}.${payload}.${signature}`;
}

/**
 * Verify RSA signature for B2B access token request.
 * stringToSign = X-CLIENT-KEY + "|" + X-TIMESTAMP
 * Verifies against the partner private key (or skips in fake mode).
 */
function verifyB2bSignature(clientKey: string, timestamp: string, signature: string): boolean {
  if (isFakeMode()) {
    return true;
  }

  const privateKey = process.env.YUKK_PRIVATE_KEY;
  if (!privateKey) {
    console.error("[webhook:b2b] YUKK_PRIVATE_KEY not configured");
    return false;
  }

  // Yukk signs with OUR public key; we verify with their public key.
  // In SNAP, the partner sends their signature using their private key,
  // and we verify using the partner's public key.
  // For now, we validate using our own private key to verify the signature
  // was generated by someone with our credentials.
  const stringToSign = `${clientKey}|${timestamp}`;

  try {
    // We need the Yukk partner's public key for verification.
    // Since Yukk sends signed requests using their private key,
    // we should have their public key. However, for initial integration,
    // we validate the signature format and timestamp.
    // The real verification uses the Yukk-provided public key.
    const yukkPublicKey = process.env.YUKK_PUBLIC_KEY;
    if (!yukkPublicKey) {
      console.error("[webhook:b2b] YUKK_PUBLIC_KEY not configured");
      return false;
    }

    const verifier = crypto.createVerify("SHA256");
    verifier.update(stringToSign);
    verifier.end();
    return verifier.verify(yukkPublicKey, signature, "base64");
  } catch {
    return false;
  }
}

/**
 * Validate that a SNAP timestamp is within ±5 minutes of now.
 * Expected format: YYYY-MM-DDTHH:mm:ss+07:00
 */
function isTimestampValid(timestamp: string): boolean {
  try {
    const parsed = new Date(timestamp);
    if (isNaN(parsed.getTime())) return false;
    const diffMs = Math.abs(Date.now() - parsed.getTime());
    return diffMs <= 5 * 60 * 1000; // ±5 minutes
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

export const webhookRoutes = new Hono();

// ── POST /v1.0/qr/qr-mpm-notify — Payment Notification ─────────────
webhookRoutes.post("/v1.0/qr/qr-mpm-notify", async (c) => {
  // Read raw body for signature verification before parsing
  const rawBody = await c.req.raw.clone().text();
  let body: YukkRawWebhookBody;

  try {
    body = JSON.parse(rawBody) as YukkRawWebhookBody;
  } catch {
    return c.json(snapError("4005201", "Invalid JSON"), 400);
  }

  // ── Signature verification ──────────────────────────────────────
  if (!isFakeMode()) {
    const signature = c.req.header("X-SIGNATURE") ?? "";
    const timestamp = c.req.header("X-TIMESTAMP") ?? "";
    const partnerId = c.req.header("X-PARTNER-ID") ?? "";
    const endpointUrl = "/v1.0/qr/qr-mpm-notify";

    const isValid = verifyYukkWebhookSignature({
      httpMethod: "POST",
      endpointUrl,
      accessToken: "", // Webhooks don't include access token in signature
      requestBody: rawBody,
      timestamp,
      signature,
    });

    if (!isValid) {
      console.warn("[webhook:notify] Invalid signature from partner:", partnerId);
      return c.json(snapError("4015201", "Unauthorized. [Invalid signature]"), 401);
    }
  }

  // ── Normalize event ─────────────────────────────────────────────
  const event = normalizeYukkWebhook(body);

  if (!event.orderId) {
    return c.json(snapError("4005201", "Missing originalPartnerReferenceNo"), 400);
  }

  // ── Find payment by orderId ─────────────────────────────────────
  const [payment] = await db
    .select()
    .from(paymentTransaction)
    .where(eq(paymentTransaction.orderId, event.orderId))
    .limit(1);

  if (!payment) {
    console.warn("[webhook:notify] Unknown order:", event.orderId);
    return c.json(snapError("4045201", "Transaction not found"), 404);
  }

  // ── Validate amount ─────────────────────────────────────────────
  const webhookAmount = Math.round(parseFloat(event.amount));
  if (webhookAmount !== payment.amount) {
    console.warn(
      `[webhook:notify] Amount mismatch for ${event.orderId}: expected ${payment.amount}, got ${webhookAmount}`,
    );
    return c.json(snapError("4005201", "Amount mismatch"), 400);
  }

  // ── Idempotency: already paid ───────────────────────────────────
  if (payment.status === "paid") {
    return c.json(snapSuccess("2005200"));
  }

  // ── Handle pending status (03) ──────────────────────────────────
  if (event.status === "pending") {
    return c.json(snapSuccess("2005200"));
  }

  // ── Handle success (00) ─────────────────────────────────────────
  if (event.status === "paid") {
    try {
      await db.transaction(async (tx) => {
        // Mark payment as paid
        await tx
          .update(paymentTransaction)
          .set({
            status: "paid",
            providerReference: event.providerReference || payment.providerReference,
            rrn: event.rrn || payment.rrn,
            paidAt: new Date(),
            rawWebhookPayload: event.raw,
            updatedAt: new Date(),
          })
          .where(eq(paymentTransaction.id, payment.id));

        // Activate subscription
        await activateSubscription(tx, {
          accountId: payment.accountId,
          plan: payment.plan as "monthly" | "yearly" | "yearly_early_bird" | "yearly_kol" | "yearly_founders",
          paymentMethod: "qris",
          paymentId: payment.id,
        });
      });

      console.info(`[webhook:notify] Payment ${event.orderId} processed — subscription activated`);
      return c.json(snapSuccess("2005200"));
    } catch (err) {
      console.error("[webhook:notify] Error processing payment:", err);
      return c.json(snapError("5005200", "Internal server error"), 500);
    }
  }

  // Unknown status — acknowledge but don't act
  console.warn(`[webhook:notify] Unknown status "${event.status}" for ${event.orderId}`);
  return c.json(snapSuccess("2005200"));
});

// ── POST /v1.0/access-token/b2b — B2B Access Token ──────────────────
webhookRoutes.post("/v1.0/access-token/b2b", async (c) => {
  const clientKey = c.req.header("X-CLIENT-KEY") ?? "";
  const signature = c.req.header("X-SIGNATURE") ?? "";
  const timestamp = c.req.header("X-TIMESTAMP") ?? "";

  // ── Validate X-CLIENT-KEY ───────────────────────────────────────
  const expectedClientKey = process.env.YUKK_PARTNER_CLIENT_ID ?? "";
  if (!isFakeMode() && clientKey !== expectedClientKey) {
    return c.json(snapError("4017301", "Unauthorized. [Unknown client]"), 401);
  }

  // ── Validate X-TIMESTAMP within ±5 minutes ─────────────────────
  if (!isFakeMode() && !isTimestampValid(timestamp)) {
    return c.json(snapError("4017303", "Unauthorized. [Invalid timestamp]"), 401);
  }

  // ── Validate X-SIGNATURE ────────────────────────────────────────
  if (!isFakeMode() && !verifyB2bSignature(clientKey, timestamp, signature)) {
    return c.json(snapError("4017302", "Unauthorized. [Invalid signature]"), 401);
  }

  // ── Generate token ──────────────────────────────────────────────
  const accessToken = generateB2bJwt();

  const response: B2bTokenResponse = {
    responseCode: "2007300",
    responseMessage: "Successful",
    accessToken,
    tokenType: "Bearer",
    expiresIn: "900",
  };

  return c.json(response);
});
