# /etc/fail2ban/filter.d/bots.conf
# Matches bad bot requests returning 444/403

[Definition]
failregex = ^<HOST> .* "(GET|POST).* HTTP.*" (444|403) .*$
            ^<HOST> -.* "(GET|POST|HEAD).* HTTP.*" 403 .*$
ignoreregex = .*(robots.txt|favicon.ico|sitemap.xml)
